config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "pages/:slug" => "pages#show", as: :page
  resources :orders do
    get :search, on: :collection
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/car.rb
class Car < ActiveRecord::Base

  has_many :line_item_groups

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :category_lineitem_groups
  has_many :line_item_groups, through: :category_lineitem_groups
  has_many :category_lineitem
  has_many :line_item, through: :category_lineitem

end

app/models/category_lineitem.rb
class CategoryLineitem < ActiveRecord::Base

  belongs_to :category
  belongs_to :line_item

end

app/models/category_lineitem_group.rb
class CategoryLineitemGroup < ActiveRecord::Base
  belongs_to :category
  belongs_to :line_item_group
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :order
  belongs_to :line_item_group

  has_many :category_lineitem
  has_many :categories, through: :category_lineitem

  accepts_nested_attributes_for :categories

  def category_names
    categories.pluck(:name).join(", ")
  end

end

app/models/line_item_group.rb
class LineItemGroup < ActiveRecord::Base
  has_many :line_item
  has_many :category_lineitem_groups
  has_many :category, through: :category_lineitem_groups
end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :line_items
  belongs_to :user

  accepts_nested_attributes_for :line_items

  before_create :generate_number

  def generate_number
    self.number = Devise.friendly_token(5)
  end

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  RESTRICTED_PATHS = [
    "/users/sign_in", "/users/sign_up", "/users/password/new",
    "/users/password/edit", "/users/confirmation", "/users/sign_out"
  ]

  after_filter :store_location

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

  def store_location
    # store last url - this is needed for post-login redirect to whatever the user last visited.
    if request.get? &&
      !RESTRICTED_PATHS.include?(request.path) &&
      !request.xhr?
      session[:previous_url] = request.fullpath
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def new
    @categories = Category.all
    @user = current_user
    @order = @user.orders.new
    @order.line_items.build
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = current_user.orders.build(order_params)

    if @order.save
      render "create"
    else
      render "new"
    end
  end

  def search
    number = params[:Number]
    @order = Order.where(number: number).first
    redirect_to order_path(@order.id)
  end

  private

    def order_params
      params.require(:order).permit(
        :address, :phone, :payment, line_items_attributes: [
          :name, :weight, :size, :total, {category_ids: []}
        ]
      )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end

  def show
    @page = Page.find_by(slug: params[:slug])
    redirect_to request.referer if @page.blank?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def pages
    @pages ||= Page.all
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/cars/_groups.html.erb
<% groups.each do |group| %>
  <% group.line_items.each do |line_item| %>
    <%= line_item.name %>
  <% end %>
<% end %>

app/views/admin/cars/_map.html.erb
<div id="map" style="width: 92%; height: 500px; margin: 50px;"></div>

<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyBY44Eg4QsCPnrBHDm8QZ2F-q0gA0y7mL0" %>
<script type="text/javascript">
  var $map = $("#map"),
      lng = <%= resource.lng %>,
      lat = <%= resource.lat %>,
      default_options ={
        center: { lat: lat, lng: lng },
        zoom: 10
      },
      map = new google.maps.Map($map[0], default_options),
      marker = new google.maps.Marker({
        map: map,
        position: { lat: lat, lng: lng },
        labelContent: "<%= resource.driver_name %>",
        labelAnchor: new google.maps.Point(50,30)
      });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>J.W Couriers - Courier Services Wrexham</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="top">
    <div id="header">
      <div class="company">
        <%= link_to "J.W Couriers", root_path %>
      </div>
    </div>
  </div>
  <div id="page">
    <div id="content">
      <div class="mainbox">
        <%= render "/shared/navbar"%>
        <%= yield %>
        <h2>Courier Services</h2>
      </div>
      <%= render "/shared/sidebar"%>
    </div>
  </div>
</body>
</html>

app/views/orders/_new_lineitem.html.erb
<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :weight, "Weight(kg)" %>
  <%= form.text_field :weight, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :size, "Size(WxHxD)" %>
  <%= form.text_field :size, class: "form-control" %>
</div>

<h3>Categories</h3>
<% @categories.each do |category| %>
  <div class="checkbox">
    <label>
      <%= form.check_box "category_ids", {multiple: true}, category.id, nil %>
      <%= category.name%>
    </label>
  </div>
<% end %>

app/views/orders/create.html.erb
<div class="mainlist">
  <h1>Your order successfuly created!</h1>

  <p>Your order number is <b><%= @order.number %></b></p>
</div>

app/views/orders/new.html.erb
<div class="mainlist">
  <%= form_for @order do |f| %>

    <div class="well">
      <h3>Order details</h3>
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :phone %>
        <%= f.text_field :phone, value: @user.phone, class: "form-control" %>
      </div>
    </div>

    <div class="well">
      <h3>Items you want to send</h3>
      <%= f.fields_for :line_items do |fli| %>
        <div id="new_lineitems">
          <%= render "new_lineitem", form: fli %>
        </div>
      <% end %>
      <button type="button" class="btn btn-success" id="button_add_lineitem">Add More Items</button>
    </div>

    <div class="well">
      <div class="form-group">
        <%= f.label :total %>
        <%= f.text_field :total, id: "total", value: 100,class: "form-control", :disabled => true  %>
      </div>
    </div>

    <div class="well">
      <h3>Payment</h3>
      <div class="radio">
        <label>
          <%= f.radio_button :payment, 'Cash' %>
          Cash
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :payment, 'Bank' %>
          Bank
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :payment, 'Online' %>
          Online
        </label>
      </div>
    </div>
    <%= f.submit "Submit", class: "btn btn-default" %>
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="mainlist">
  <h1>Track <%= @order.number%></h1>

</div>

app/views/pages/index.html.erb
<div class="mainlist">
  <h1>Local Courier<br />J.W Couriers in Wrexham</h1>
  <ul>
    <li>Independent local courier</li>
    <li>Same day specialist</li>
    <li>Local &amp; nationwide</li>
    <li>Parcels to small pallets</li>
    <li>Personal door to door service</li>
    <li>Goods in transit insurance</li>
  </ul>
  <div class="staticimg"><%= image_tag "image_5766_l1065_c.jpg"%></div>
  <div class="cl"></div>

  <div class="sepline"><%= image_tag "flourish.gif"%></div>
  <div class="contactbox subcontact">
    <dl>
      <dt>J.W Couriers</dt>
      <dd>      123 Mold Road <br/> 
       Wrexham<br/>  
       LL113AT <br/>    </dd>
       <dd class="add">Tel: 07890 123456</dd>
       <dd>  </dd>
     </dl>
  </div>
</div>

app/views/pages/show.html.erb
<div class="mainlist">
  <h1><%= @page.title %></h1>
  <p><%= raw @page.content %></p>
</div>

app/views/shared/_navbar.html.erb
<div class="navigation">
  <nav class="navbar navigation">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav main_nav">
        <% pages.each do |page|%>
          <li><%= link_to page.title, page_path(page.slug) %></li>
        <% end %>
        <li><%= link_to "Make order", new_order_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
      <div class="callbox">Your local specialist <span>07890 123456</span></div>
      <div class="servicebox service2">
        <div class="service2top">
          <div class="service2btm">
            <strong class="title">Track your order</strong>
             <%= form_tag('/orders/search', method: :get) do %>
              <%= text_field_tag "Number"%>
             <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>